name: CI

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  coverage:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        python-version: ["3.11", "3.12", "3.13"]
    env:
          LATEST_PYTHON_VERSION: "3.13"
    steps:
      - name: Check out diffpy.labpdfproc
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: Install diffpy.labpdfproc and requirements for Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
          conda install --file requirements/test.txt
          pip install -r requirements/pip.txt
          python -m pip install . --no-deps

      - name: Install diffpy.labpdfproc and requirements for non-Linux
        if: runner.os != 'Linux'
        run: |
          conda install --file requirements/test.txt
          pip install -r requirements/pip.txt
          python -m pip install . --no-deps

      - name: Validate diffpy.labpdfproc
        run: |
          pytest --cov
          coverage report -m
          codecov

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == env.LATEST_PYTHON_VERSION
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
